apiVersion: v1
kind: Service
metadata:
  name: py--backend
  namespace: dev-one
  labels:
    app.kubernetes.io/name: py--backend
    app.kubernetes.io/managed-by: deepagent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: py--backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
